//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgotPasswordTryIt.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/forgotPassowrd", ReplyAction="http://tempuri.org/IService1/forgotPassowrdResponse")]
        bool forgotPassowrd(System.Collections.Generic.Dictionary<string, string> userCredentials, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/forgotPassowrd", ReplyAction="http://tempuri.org/IService1/forgotPassowrdResponse")]
        System.Threading.Tasks.Task<bool> forgotPassowrdAsync(System.Collections.Generic.Dictionary<string, string> userCredentials, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveData", ReplyAction="http://tempuri.org/IService1/saveDataResponse")]
        string saveData(System.Collections.Generic.Dictionary<string, string> userInfo, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveData", ReplyAction="http://tempuri.org/IService1/saveDataResponse")]
        System.Threading.Tasks.Task<string> saveDataAsync(System.Collections.Generic.Dictionary<string, string> userInfo, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ForgotPasswordTryIt.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ForgotPasswordTryIt.ServiceReference1.IService1>, ForgotPasswordTryIt.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool forgotPassowrd(System.Collections.Generic.Dictionary<string, string> userCredentials, string fileName) {
            return base.Channel.forgotPassowrd(userCredentials, fileName);
        }
        
        public System.Threading.Tasks.Task<bool> forgotPassowrdAsync(System.Collections.Generic.Dictionary<string, string> userCredentials, string fileName) {
            return base.Channel.forgotPassowrdAsync(userCredentials, fileName);
        }
        
        public string saveData(System.Collections.Generic.Dictionary<string, string> userInfo, string fileName) {
            return base.Channel.saveData(userInfo, fileName);
        }
        
        public System.Threading.Tasks.Task<string> saveDataAsync(System.Collections.Generic.Dictionary<string, string> userInfo, string fileName) {
            return base.Channel.saveDataAsync(userInfo, fileName);
        }
    }
}
