//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProfile", ReplyAction="http://tempuri.org/IService1/editProfileResponse")]
        System.Collections.Generic.Dictionary<string, string> editProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProfile", ReplyAction="http://tempuri.org/IService1/editProfileResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> editProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setName", ReplyAction="http://tempuri.org/IService1/setNameResponse")]
        void setName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setName", ReplyAction="http://tempuri.org/IService1/setNameResponse")]
        System.Threading.Tasks.Task setNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApplicationTest.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApplicationTest.ServiceReference1.IService1>, ConsoleApplicationTest.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> editProfile() {
            return base.Channel.editProfile();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> editProfileAsync() {
            return base.Channel.editProfileAsync();
        }
        
        public void setName(string name) {
            base.Channel.setName(name);
        }
        
        public System.Threading.Tasks.Task setNameAsync(string name) {
            return base.Channel.setNameAsync(name);
        }
    }
}
